- name: Install GitLab Runner (Windows)
  import_tasks: install-windows.yml

- name: (Windows) Delete runners which were removed in GitLab
  win_command: "{{ gitlab_runner_executable }} verify --delete"
  args:
    chdir: "{{ gitlab_runner_config_file_location }}"
  register: verified_runners
  changed_when: '"Updated " in verified_runners.stderr'
  check_mode: no

- name: (Windows) Register GitLab Runner
  include_tasks: register-runner-windows.yml
  vars:
    - actual_gitlab_runner_name: "{{ gitlab_runner.name|default(ansible_hostname+'-'+gitlab_runner_index|string) }}"
  when: gitlab_runner.token is defined or gitlab_runner_registration_token | string | length > 0
  loop: "{{ gitlab_runner_runners }}"
  loop_control:
    index_var: gitlab_runner_index
    loop_var: gitlab_runner

- name: (Windows) Set global options
  import_tasks: global-setup-windows.yml

- name: (Windows) Configure GitLab Runner
  include_tasks: config-runners-windows.yml
  when: gitlab_runner_config_update_mode == 'by_config_toml'

- name: (Windows) Start GitLab Runner
  win_command: "{{ gitlab_runner_executable }} start"
  args:
    chdir: "{{ gitlab_runner_config_file_location }}"